### ISSUE TITLE
Requirements in README are out of date

### ISSUE THREAD

**Issue by pjmonks** [MauroDataMapper/mdm-application-build#11]
The software requirements in the README currently state these dependencies:

> Grails 4.0.6 +
Gradle 6.7.1
Java OpenJDK 12

These are incorrect now, they should match what is in the MauroDataMapper/mdm-core README:

> Grails 5.1.1+
Gradle 7.3.3
Java 17

**Comment by jamesrwelch** [comment]
Thank you - good spot - we'll get that corrected.
